Repository learner-next/sql-challenge, pull requests merged in 2023-11, with the labels that each got.

#60 chore: rename title
  index.html
Labels: size/XS

#61 workflow: add lint before commit
  package.json
Labels: size/XS

#62 feat: insert
  src/challenges/createChallenges/index.ts
  src/challenges/createChallenges/insert-values/content.md
  src/challenges/createChallenges/insert-values/index.ts
  src/challenges/createChallenges/insert-values/initSql.sql
Labels: size/L

#63 feat: add playground
  bun.lockb
  package.json
  src/App.tsx
  src/components/common/SqlEditor.tsx
  src/pages/SqlPlayground.tsx
  src/router.ts
Labels: size/L

#64 chore: show all sql challenges
  bun.lockb
  package.json
  src/components/ui/tabs.tsx
  src/components/ui/tag.tsx
  src/pages/Challenges.tsx
  src/pages/SqlChallenges.tsx
  src/router.ts
Labels: size/L

#65 docs: update readme
  README.md
Labels: size/XS

#66 fix: add search
  bun.lockb
  package.json
  src/App.tsx
  src/challenges/createChallenges/insert-values/index.ts
  src/components/common/SqlChallengeSearch.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/popover.tsx
  src/components/ui/separator.tsx
  src/type.ts
  src/utils.ts
Labels: size/L

#67 docs: readme
  README.md
Labels: size/XS

#68 feat: data types
  src/challenges/createChallenges/data-types/content.md
  src/challenges/createChallenges/data-types/index.ts
  src/challenges/createChallenges/data-types/initSql.sql
  src/challenges/createChallenges/index.ts
  src/sql/result.ts
Labels: size/L

#69 feat: create view
  public/view.png
  src/challenges/createChallenges/create-view/content.md
  src/challenges/createChallenges/create-view/index.ts
  src/challenges/createChallenges/create-view/initSql.sql
  src/challenges/createChallenges/index.ts
Labels: size/L

#70 Chore/update
  src/challenges/updateChallenges/index.ts
  src/challenges/updateChallenges/update-table/content.md
  src/challenges/updateChallenges/update-table/index.ts
  src/challenges/updateChallenges/update-table/initSql.sql
  src/components/common/SqlChallengePage.tsx
  src/components/common/SqlEditor.tsx
  src/components/common/SqlResult.tsx
  src/pages/UpdateChallenge.tsx
  src/sql/result.ts
  src/type.ts
  src/utils.ts
Labels: size/L

#71 chore: optimization
  src/challenges/createChallenges/create-table/index.ts
  src/challenges/createChallenges/create-view/index.ts
  src/challenges/createChallenges/data-types/index.ts
  src/challenges/createChallenges/insert-values/index.ts
  src/challenges/createChallenges/table-constraints/index.ts
  src/challenges/createChallenges/table-index/index.ts
  src/challenges/selectChallenges/select-aggregate/index.ts
  src/challenges/selectChallenges/select-all-any/index.ts
  src/challenges/selectChallenges/select-and-or/index.ts
  src/challenges/selectChallenges/select-as/index.ts
  src/challenges/selectChallenges/select-base/index.ts
  src/challenges/selectChallenges/select-case/index.ts
  src/challenges/selectChallenges/select-cross-join/index.ts
  src/challenges/selectChallenges/select-distinct/index.ts
  src/challenges/selectChallenges/select-exists/index.ts
  src/challenges/selectChallenges/select-field/index.ts
  src/challenges/selectChallenges/select-full-join/index.ts
  src/challenges/selectChallenges/select-group-by/index.ts
  src/challenges/selectChallenges/select-having/index.ts
  src/challenges/selectChallenges/select-in/index.ts
  src/challenges/selectChallenges/select-inner-join/index.ts
  src/challenges/selectChallenges/select-left-join/index.ts
  src/challenges/selectChallenges/select-like/index.ts
  src/challenges/selectChallenges/select-limit-offset/index.ts
  src/challenges/selectChallenges/select-null/index.ts
  src/challenges/selectChallenges/select-order-by/index.ts
  src/challenges/selectChallenges/select-self-join/index.ts
  src/challenges/selectChallenges/select-subquery/index.ts
  src/challenges/selectChallenges/select-union/index.ts
  src/challenges/selectChallenges/select-where/index.ts
  src/challenges/selectChallenges/select-window/index.ts
  src/challenges/updateChallenges/update-table/index.ts
  src/components/common/SqlChallengePage.tsx
  src/components/common/SqlEditor.tsx
  src/components/common/SqlResult.tsx
  src/pages/CreateChallenge.tsx
  src/pages/SelectChallenge.tsx
  src/pages/SqlPlayground.tsx
  src/sql/result.ts
  src/type.ts
Labels: size/L

#72 feat: update values
  src/App.tsx
  src/challenges/updateChallenges/index.ts
  src/challenges/updateChallenges/update-table/content.md
  src/challenges/updateChallenges/update-values/content.md
  src/challenges/updateChallenges/update-values/index.ts
  src/challenges/updateChallenges/update-values/initSql.sql
Labels: size/L

#73 feat: update index
  src/challenges/createChallenges/table-index/content.md
  src/challenges/updateChallenges/update-table/content.md
Labels: size/S

#74 feat: update challenges
  src/pages/SqlChallenges.tsx
Labels: size/XS

#75 feat: update delete
  src/challenges/deleteChallenges/delete-table/content.md
  src/challenges/deleteChallenges/delete-table/index.ts
  src/challenges/deleteChallenges/delete-table/initSql.sql
  src/challenges/deleteChallenges/index.ts
  src/components/common/SqlChallengeSearch.tsx
  src/pages/DeleteChallenge.tsx
  src/pages/SqlChallenges.tsx
Labels: size/L

#76 feat: delete values
  src/challenges/deleteChallenges/delete-columns/content.md
  src/challenges/deleteChallenges/delete-columns/index.ts
  src/challenges/deleteChallenges/delete-columns/initSql.sql
  src/challenges/deleteChallenges/delete-values/content.md
  src/challenges/deleteChallenges/delete-values/index.ts
  src/challenges/deleteChallenges/delete-values/initSql.sql
  src/challenges/deleteChallenges/index.ts
Labels: size/M

#77 feat: remove type
  src/challenges/createChallenges/create-table/index.ts
  src/challenges/createChallenges/create-view/index.ts
  src/challenges/createChallenges/data-types/index.ts
  src/challenges/createChallenges/insert-values/index.ts
  src/challenges/createChallenges/table-constraints/index.ts
  src/challenges/createChallenges/table-index/index.ts
  src/challenges/deleteChallenges/delete-columns/index.ts
  src/challenges/deleteChallenges/delete-values/index.ts
  src/challenges/selectChallenges/select-aggregate/index.ts
  src/challenges/selectChallenges/select-all-any/index.ts
  src/challenges/selectChallenges/select-and-or/index.ts
  src/challenges/selectChallenges/select-as/index.ts
  src/challenges/selectChallenges/select-base/index.ts
  src/challenges/selectChallenges/select-case/index.ts
  src/challenges/selectChallenges/select-cross-join/index.ts
  src/challenges/selectChallenges/select-distinct/index.ts
  src/challenges/selectChallenges/select-exists/index.ts
  src/challenges/selectChallenges/select-field/index.ts
  src/challenges/selectChallenges/select-full-join/index.ts
  src/challenges/selectChallenges/select-group-by/index.ts
  src/challenges/selectChallenges/select-having/index.ts
  src/challenges/selectChallenges/select-in/index.ts
  src/challenges/selectChallenges/select-inner-join/index.ts
  src/challenges/selectChallenges/select-left-join/index.ts
  src/challenges/selectChallenges/select-like/index.ts
  src/challenges/selectChallenges/select-limit-offset/index.ts
  src/challenges/selectChallenges/select-null/index.ts
  src/challenges/selectChallenges/select-order-by/index.ts
  src/challenges/selectChallenges/select-self-join/index.ts
  src/challenges/selectChallenges/select-subquery/index.ts
  src/challenges/selectChallenges/select-union/index.ts
  src/challenges/selectChallenges/select-where/index.ts
  src/challenges/selectChallenges/select-window/index.ts
  src/challenges/updateChallenges/update-table/index.ts
  src/challenges/updateChallenges/update-values/index.ts
  src/components/common/SqlChallengeSearch.tsx
  src/components/common/SqlQuestion.tsx
  src/pages/SqlPlayground.tsx
  src/type.ts
Labels: size/M

#78 fix: typo
  src/pages/SqlChallenges.tsx
Labels: size/XS
