Repository learner-next/sql-challenge, pull requests merged in 2023-10, with the labels that each got.

#35 feat: self join
  src/challenges/mainChallenges.ts
  src/challenges/select-self-join/content.md
  src/challenges/select-self-join/index.ts
  src/challenges/select-self-join/initSql.sql
Labels: size/L

#36 feat: cross join
  src/challenges/mainChallenges.ts
  src/challenges/select-cross-join/content.md
  src/challenges/select-cross-join/index.ts
  src/challenges/select-cross-join/initSql.sql
  src/challenges/select-self-join/index.ts
Labels: size/L

#37 chore: make fix linter error easily
  package.json
Labels: size/XS

#40 workflow: eslint
  package.json
Labels: size/S

#38 chore: add more route
  src/App.tsx
  src/components/common/SqlQuestion.tsx
  src/pages/CreateChallenge.tsx
  src/pages/DeleteChallenge.tsx
  src/pages/SqlChallenge.tsx
  src/pages/UpdateChallenge.tsx
  src/router.ts
Labels: size/M

#41 workflow: action of update deps bot
  .github/dependabot.yml
Labels: size/XS

#42 docs: update readme
  .gitignore
  README.md
  image.png
  index.html
  public/logo.jpg
  public/sql-challenge.svg
  public/vite.svg
  sql db.svg
  sql-challenge.svg
  src/App.tsx
Labels: size/L

#43 docs: update readme
  README.md
Labels: size/S

#45 fix: question router
  src/components/common/SqlEditor.tsx
  src/components/common/SqlQuestion.tsx
  src/pages/SelectChallenge.tsx
Labels: size/S

#46 feat: add window function
  src/App.tsx
  src/challenges/index.ts
  src/challenges/selectChallenges/index.ts
  src/challenges/selectChallenges/select-window/content.md
  src/challenges/selectChallenges/select-window/index.ts
  src/challenges/selectChallenges/select-window/initSql.sql
  src/components/common/SqlQuestion.tsx
  src/pages/SelectChallenge.tsx
Labels: size/L

#47 docs: update readme
  README.md
  image-1.png
  image-2.png
  src/components/common/SqlQuestion.tsx
Labels: size/S

#49 fix: update file path
  README.md
  image-1.png
  public/show-select.png
Labels: size/XS

#51 fix: cors
  nginx.conf
  vercel.json
Labels: size/M

#52 fix: build
  src/sql/db.ts
  vercel.json
  vite.config.ts
Labels: size/S

#53 fix: sql.js static
  public/static/sql-wasm.wasm
  src/sql/db.ts
Labels: size/XS

#54 feat: create table
  src/App.tsx
  src/challenges/createChallenges/create-table/content.md
  src/challenges/createChallenges/create-table/index.ts
  src/challenges/createChallenges/index.ts
  src/challenges/createChallenges/insert-values/content.md
  src/challenges/createChallenges/insert-values/index.ts
  src/challenges/createChallenges/insert-values/initSql.sql
  src/components/common/SqlEditor.tsx
  src/pages/CreateChallenge.tsx
  src/sql/result.ts
  src/utils.ts
Labels: size/L

#58 chore: use alasql
  bun.lockb
  package.json
  src/challenges/createChallenges/table-index/initSql.sql
  src/challenges/selectChallenges/select-aggregate/initSql.sql
  src/challenges/selectChallenges/select-and-or/initSql.sql
  src/challenges/selectChallenges/select-base/initSql.sql
  src/challenges/selectChallenges/select-distinct/initSql.sql
  src/challenges/selectChallenges/select-field/initSql.sql
  src/challenges/selectChallenges/select-group-by/initSql.sql
  src/challenges/selectChallenges/select-having/initSql.sql
  src/challenges/selectChallenges/select-in/initSql.sql
  src/challenges/selectChallenges/select-like/initSql.sql
  src/challenges/selectChallenges/select-limit-offset/initSql.sql
  src/challenges/selectChallenges/select-null/initSql.sql
  src/challenges/selectChallenges/select-order-by/initSql.sql
  src/challenges/selectChallenges/select-self-join/initSql.sql
  src/challenges/selectChallenges/select-where/initSql.sql
  src/components/common/SqlEditor.tsx
  src/components/common/SqlResult.tsx
  src/pages/CreateChallenge.tsx
  src/pages/SelectChallenge.tsx
  src/sql/db.ts
  src/sql/result.ts
  src/type.ts
Labels: size/L
